version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=kenny
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - /postgres_data:/var/lib/postgresql


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

volumes:
  postgresql-volume:
    external: true
      